### ISSUE TITLE
Please provide signed assembly

### ISSUE THREAD

**Issue by shatl** [Microsoft/Microsoft.IO.RecyclableMemoryStream#10]
Unfortunately, current version can not be referenced from signed assemblies.

**Comment by doubleyewdee** [comment]
I believe you're referring to the nuget package here. Let me look into how we can reasonably do this. Since this is our first OSS package we went ahead and got the unsigned package out there. Need to make sure we can maintain a consistent/secure signing solution that any other Microsoft maintainers can pick up. Thanks, we'll get back to you!

**Comment by shatl** [comment]
Hi guys, any updates on this?

**Comment by HugoLemieux** [comment]
Hi guys, I have the same problem since we are using signed assemblies and I want to know if you have any updates on this?

**Comment by shatl** [comment]
Hi guys, any updates so far?

**Comment by doubleyewdee** [comment]
Yeah. We should have a 1.1 version with a few bugfixes and a signed assembly early next week.

We over here are still learning how to code sign "right" in the company and that took longer than I anticipated. I do apologize for the wait as I know this is a popular request. Going forward we'll get this right for y'all.

**Comment by shatl** [comment]
Great news! 
Waiting to see it on NuGet. Thanks!

**Comment by shatl** [comment]
Thanks a lot guys!
