### ISSUE TITLE
Questions about defaults

### ISSUE THREAD

**Issue by MrJul** [Microsoft/Microsoft.IO.RecyclableMemoryStream#14]
I'm a little surprised that the default block size is 128 KB, effectively allocating these directly inside the large object heap. Isn't one of the purpose of this library avoiding LOH allocations?

I know it's configurable so that's not a big deal. :) I'm just curious to know how these defaults were chosen.

**Comment by doubleyewdee** [comment]
No, actually the intent is to make LOH allocations less expensive which is why the default is 128k.

Sent from Outlook




On Sun, Apr 26, 2015 at 4:14 PM -0700, "Julien Lebosquain" <notifications@github.com> wrote:
I'm a little surprised that the default block size is 128 KB, effectively allocating these directly inside the large object heap. Isn't one of the purpose of this library avoiding LOH allocations?

I know it's configurable so that's not a big deal. :) I'm just curious to know how these defaults were chosen.


---
Reply to this email directly or view it on GitHub:
https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream/issues/14

**Comment by MrJul** [comment]
Thank you for the quick response. That makes sense.
