### ISSUE TITLE
Improve handling of MaximumFreeSmallPoolBytes

### ISSUE THREAD

**Issue by szarykott** [microsoft/Microsoft.IO.RecyclableMemoryStream#149]
Running an application in the production web server at my company, we discovered that RecyclableMemoryStreamManager was responsible for a huge memory leak. It was unexpected as this library was meant to lower resource usage by reusing memory, not leaking it.

We quickly found that the issue was partially on our side. We did not set MaximumFreeSmallPoolBytes setting, thus causing the memory leak. While documentation mentions it, it is not highlighted enough in my opinion, especially that unlimited pool size is a possibility of a leak.

Would it be possible to set MaximumFreeSmallPoolBytes (and possibly its large buffer counterpart) to some reasonable initial value or at least highlight the importance of explicitly setting those in documentation with warning that not doing so might cause a memory leak?

**Comment by benmwatson** [comment]
I'm not sure what a reasonable default would be. For us here in Bing, we set it to a few gigabytes because we want to handle occasional huge spikes in traffic. But for most applications, that would be insane overkill.

A few hundred MB? Maybe a warning event to the log indicating pool growth is unbounded as configured? Not sure anyone looks at the log.

Some documentation changes to highlight this? Maybe in both the xml/intellisense and in the readme? Perhaps RMSManger ctor overload that takes these parameters?

I'm open to other ideas.

From: Radosław Kot ***@***.***>
Sent: Wednesday, March 24, 2021 2:56 AM
To: microsoft/Microsoft.IO.RecyclableMemoryStream ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/Microsoft.IO.RecyclableMemoryStream] Improve handling of MaximumFreeSmallPoolBytes (#149)


Running an application in the production web server at my company, we discovered that RecyclableMemoryStreamManager was responsible for a huge memory leak. It was unexpected as this library was meant to lower resource usage by reusing memory, not leaking it.

We quickly found that the issue was partially on our side. We did not set MaximumFreeSmallPoolBytes setting, thus causing the memory leak. While documentation mentions it, it is not highlighted enough in my opinion, especially that unlimited pool size is a possibility of a leak.

Would it be possible to set MaximumFreeSmallPoolBytes (and possibly its large buffer counterpart) to some reasonable initial value or at least highlight the importance of explicitly setting those in documentation with warning that not doing so might cause a memory leak?

-
