### ISSUE TITLE
Why is length and position an int and not a long?

### ISSUE THREAD

**Issue by ninjasource** [microsoft/Microsoft.IO.RecyclableMemoryStream#46]
hi, I was wondering why and an int was chosen for the datatype for the position and length of the stream when a long would allow us to use streams larger than 2GB.

**Comment by ninjasource** [comment]
This pertains to the SafeRead function that mutates streamPosition. If streamPosition was a long you would be free to upgrade the RecyclableMemoryStream class without having to change the signature.

**Comment by doubleyewdee** [comment]
There are other reasons you cannot use streams larger than 2GB. I've looked at supporting this but the cost is relatively high (e.g. you cannot retrieve a single large contiguous buffer due to design limitations in .NET arrays) which is why the current implementation exists the way it does. If there is strong desire for supporting large non-contiguous streams we can look at that, and as always patches are welcome.

**Comment by ninjasource** [comment]
Thanks, I would think that throwing an exception when GetBuffer or ToArray is called on memory streams larger than 2GB would be better than restricting the API but I guess, like you say, devs are not using this for large streams so its a moot point.

**Comment by doubleyewdee** [comment]
Not at this time certainly. Pooling might be interesting in these instances, so if you have a specific use case I'd like to hear about it at least. I did discuss this with Ben about a year ago but we failed to come up with a compelling reason to make the change and so have not done it.

**Comment by benmwatson** [comment]
Since no action is required at this time, closing the issue.
