### ISSUE TITLE
Create abstract interface for RecyclableMemoryStreamManager

### ISSUE THREAD

**Issue by shatl** [Microsoft/Microsoft.IO.RecyclableMemoryStream#6]
Please create abstract interface for RecyclableMemoryStreamManager public surface to facilitate unit-testing.

**Comment by doubleyewdee** [comment]
After discussing this with Ben we are going to avoid doing this. There are a lot of great mocking libraries that should obviate the need for an interface here, and unfortunately adding interfaces is a non-zero performance cost for every call site. For users who do wish to mock via interfaces or use separate implementations our recommendation would be to create and provide your own wrappers since this is a pretty simple library.
